name: Rust

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cargo install cargo-audit
    - name: Audit
      run: cargo audit
